#!/bin/python
def partition(ar): 
    p = ar[0]
    equal = []
    left = []
    right = []
    for i in ar:
        if i == p:
            equal.append(i)
        elif i < p:
            left.append(i)
        else:
            right.append(i)
    ll = left + equal + right
    for u in ll:
        print u,

m = input()
ar = [int(i) for i in raw_input().strip().split()]
partition(ar)
